#spring:
#  application:
#    name: authorization-code
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: authorization-code-client
#            client-secret: your-client-secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/demo-realm
#            authorization-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/certs
#            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
    com.example: DEBUG

server:
  port: 8081